[package]
name = "privaxy_Study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["time", "rt", "rt-multi-thread", "macros"] }
env_logger = "0.10.1"
